from random import randint
tentativas = 1
computador = randint(0,10)

print('O computador pensou em um número entre 0 a 10, tente adivinhar: ',end='')
r=int(input())

if r == computador:
   
    print('Parabéns, você acertou de primeira, PARABÉNS !!!')

else:

    while r != computador:
        print('Você errou, tente novamente: ',end='')
        r=int(input())
        tentativas += 1

        if r == computador:
         print('Parabéns, você acertou, com um total de {} tentativas'.format(tentativas))

#Este programa em Python permite que o usuário tente adivinhar um número entre 0 e 10, gerado
#aleatoriamente pelo computador. Se o usuário acertar na primeira tentativa, uma mensagem de
#parabéns é exibida. Caso contrário, o programa continua pedindo para o usuário tentar adivinhar
#o número até que ele acerte. Após o acerto, o programa informa o número total de tentativas necessárias.


#This Python program allows the user to guess a number between 0 and 10, randomly generated by the computer.
#If the user guesses correctly on the first attempt, a congratulations message is displayed. Otherwise, the
#program continues to prompt the user to guess the number until they guess correctly. After the correct guess,
#the program informs the total number of attempts it took.